// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usacpcrbbhcdnbhynowg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzYWNwY3JiYmhjZG5iaHlub3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjUxODYsImV4cCI6MjA3MzEwMTE4Nn0.ED9SrBUlfy5FtSY4SesBk9mRpVpLOxKUtLUEb26zb3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});